import { Box, Heading } from '@chakra-ui/react';

import { globalMaxWidthBox } from '../styles/common';
import { DemosPageContent } from '../components/DemosPageContent';
import Head from 'next/head';
import React from 'react';

const Demos = () => {
  return (
    <Box {...globalMaxWidthBox} p={5}>
      <Head>
        <title>Demo | Japanese Moji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DemosPageContent />
    </Box>
  );
};

export default Demos;
